name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - Puyodead1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe with as much detail as you can exactly what happened
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected Result
      description: What do you expect to happen if the bug didn't occur?
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: Branch
      description: What branch are you using?
      options:
        - "master/main"
        - Other (Enter below)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating systems are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux/Unix
        - MacOS
        - Other (Enter Below)
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. Remember to censor sensitive information before submitting!
      render: shell
  - type: textarea
    id: other-information
    attributes:
      label: Other information
      description: Enter other information here such as an unlisted OS or branch
