name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
            suffix: win-amd64.exe
          - os: windows
            arch: 386
            suffix: win32.exe
          - os: linux
            arch: amd64
            suffix: linux-amd64
          - os: linux
            arch: 386
            suffix: linux-386
          - os: linux
            arch: arm
            suffix: linux-arm
          - os: linux
            arch: arm64
            suffix: linux-arm64
          - os: darwin
            arch: amd64
            suffix: darwin-amd64
          # - os: darwin
          #   arch: arm64
          #   suffix: darwin-arm64

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build ${{ matrix.os }} ${{ matrix.arch }}
      run: env GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o udemy-dl-go-${{ matrix.suffix }} -v ./...

    - uses: actions/upload-artifact@v2
      with:
        name: udemy-dl-go-${{ matrix.suffix }}
        path: udemy-dl-go-${{ matrix.suffix }}