name: "TODO Issue Creator"
on: 
  push:
  pull_request:
  workflow_call:
jobs:
  run:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.6.3"
        id: "todo"
        with:
          AUTO_ASSIGN: true
